#!/bin/sh -exu
CHANNEL=$1

git submodule update --init Madek
cd Madek
git fetch
git submodule foreach --recursive 'git reset --hard HEAD'
git reset --hard "origin/${CHANNEL}"
git submodule update --recursive deploy
